apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dp002
    app.kubernetes.io/instance: dp002-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: dp002-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: dp002-app
  template:
    metadata:
      labels:
        app: dp002-app
    spec:
      containers:
        - image: 325583868777.dkr.ecr.ca-central-1.amazonaws.com/dp002-repository:latest
          imagePullPolicy: Always
          name: dp002-app
          ports:
            - containerPort: 3000
