apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: cicd-demo
    app.kubernetes.io/instance: cicd-demo-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: cicd-demo-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: cicd-demo
  template:
    metadata:
      labels:
        app: dp002-app
    spec:
      containers:
        - image: 325583868777.dkr.ecr.ca-central-1.amazonaws.com/cicd-demo:latest
          imagePullPolicy: Always
          name: dp002-app
          ports:
            - containerPort: 3000
