apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: dp002-app
    app.kubernetes.io/instance: dp002-app-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: dp002-app
spec:
  selector:
    app: dp002-app
  ports:
   -  protocol: TCP
      port: 8080
      targetPort: 3000
